<?php

namespace damainpotepuh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends EntityRepository
{
    public function findAll() 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT c FROM damainpotepuhCoreBundle:subcategory c ORDER BY c.name DESC')
                    ->getResult();
    }
}
