<?php

namespace damainpotepuh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends EntityRepository
{
    
    public function findAll() 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT s FROM damainpotepuhCoreBundle:subcategory s ORDER BY s.name DESC')
                    ->getResult();
    }
    
    public function findSubcategoryByName($name)
    {
        return $this->getEntityManager()
                    ->createQuery('
                        SELECT s FROM damainpotepuhCoreBundle:subcategory s
                        WHERE s.name = :name'
                    )
                    ->setParameter('name', $name)
                    ->getResult();
    }
}
