<?php

namespace damainpotepuh\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class VideoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \damainpotepuh\AdminBundle\Controller\VideoController();
        return $instance;
    }
}
